batch_size: 128
learning_rate: 0.1
epochs: 95
sigma: 5.
lambda_x: 0.
lambda_y: 0.
seed: 1234
k_type_y: linear

device: cuda
model: wideresnet-28-10 # wideresnet28-10, resnet50, resnet18
data_code: svhn # svhn, cifar100, cifar10
model_file: test.pt
checkpoint: null
task: pre-train
training_type: hsictrain

lr_scheduler :  cosine
warmup :  False
warmup_lr :  0.0001
warmup_epochs :  5
mix_up :  False
alpha :  0.3
smooth :  True
smooth_eps :  0.1
log_batch_interval: 10
verbose: 0
exp_index: null
do_training: True

xentropy_weight: 0.
hsic_weight: 1.

attack_type: pgd
epsilon: 8
pgd_steps: 10
pgd_alpha: 2

adv_method: trades # trades, mart, pgd
